QUESTIONS = [
    "What are three things I’m grateful for, no matter how small?",
    "What are my top three strengths? What are three things I can improve on?",
    "What is the one thing you wish you had done differently today?",
    "What event or milsetone are you looking forward to?",
    "What's the best news you received recently?",
    "Who in your life is most like you?",   
    "What relationship in your life do you wish you could improve?",
    "Who is the first person you thought of today?",
    "What promise have you kept?",
    "With whom did you have a meaningful conversation today?",
    "What lie have you told recently?",
    "Who has always been your support?",
    "Who surprised you today?",
    "Who makes you feel appreciated?",
    "How soundly do you sleep?",
    "How many true friends do you have?",
    "Who had your back today?",
    "Who is still your friend you're surprised about?",
    "What's the biggest change in your life since last year?",
    "Write down all of the reasons why you are proud of yourself.",
    "What are three things I appreciate about nature?",
    "Do I love myself? What do I need to do to unconditionally love myself?",
    "What is a simple delight I have been enjoying lately?",
    "What are the biggest challenges you’re facing right now? How can you work to overcome them?",
    "What is your biggest fear?",
    "What are your daily habits? How do they contribute to your overall well-being?",
    "What are your biggest regrets? How can you learn from them?",
    "What brings me joy?",
    "Do you feel like your life is moving in the right direction, or the direction you want it to move towards?",
    "What do I need to stop doing and start doing?",
    "What does success mean to you?",
    "What is something I am grateful to have learned?",
    "I am proud of myself for ___.",
    "Write a letter of gratitude to someone you’ve always wanted to thank.",
    "What do I love about where I live?",
    "What activities do I enjoy?",
    "Do I believe I am beautiful and worthy of love? If not, where did I learn that from?",
    "What is your biggest source of stress? How can you manage it?",
    "What is a happy memory from my childhood?",
    "What are your non-negotiables in life? In relationships? In your personal habits? At work? At home?",
    "Who has supported me during difficult times?",
    "What do I appreciate about myself?",
    "What do I have now that I dreamed of having years ago?",
    "What does 'success' mean to me?",
    "In what ways have I grown as a person over the last year?",
    "If I had all the money and time in the world, what would I be doing?",
    "What is your relationship with yourself? How can you cultivate more self-love and acceptance?",
    "Imagine that you are living your dream life right now. Describe your day and activities in detail. What does your day’s schedule look like? What are you wearing? Who are the people around you? What are you eating/cookbook?",
    "What is your relationship with others? Do you have a loving support system, or are you feeling alone and lonely?",
    "What is one thing I can do today to get closer to my goal?",
    "Have there been any significant changes in your life in the last year? Have they had a lingering impact on you and your life?",
    "What do I want my life to look like in five or ten years?",
    "What are your biggest accomplishments? How did you achieve them?",
    "What are your core values? How do they shape your choices and actions?",
    "What are three reasons I am glad to be alive?",
    "What do I believe to be true about myself? Is it hurting or helping me?",
    "Do you feel like you are missing something in your social life or is your sense of community feeling weak? If this is something you are struggling with, what can you do to change that?",
    "What is a talent or skill that I’m grateful to possess?",
    "If someone tries to give me money or buy me a meal, do I accept or refuse? If I have trouble accepting money, where did that come from?",
    "What goals did you have, say, 5 years ago? Do you still want the same things?",
    "A cluttered or messy environment can represent a cluttered mind. What is one thing I can do right now to make my environment cleaner/more organized?",
    "What is the best thing that happened this past week?",
    "Who or what is stopping me from doing what I want to do? Do I need them in my life? How can I change my environment or my mindset to move past them and their influence?",
    "What makes me feel excited to get up in the morning?",
    "What am I grateful for in this moment?",
    "What is one good thing that I often take for granted?",
    "What am I afraid of?",
    "What do I need to let go of from the past?",
    "Who do you want to be like when you grow up?",
    "What feels good about your life right now?",
    "How do you typically deal with negative emotions? Do you have a healthy outlet or is it more of a coping mechanism?",
    "What do I really want in life? Not what my family, friends, or society think I should want… what do I want?",
    "What is your biggest source of joy? How can you cultivate more of it?",
    "Would your younger self be proud of you?",
    "Who do I need to thank?",
    "Who are the people that you want to do life with?",
    "Do you keep a gratitude journal? What are you most grateful for in your life?",
    "What made me smile today?",
    "What 5 lessons would you tell your 18-year-old self?",
    "When someone gives me a compliment, do I say 'thank you' or refuse it? If I refuse it, where did I learn that from?",
    "What are your biggest strengths? How can you use them to achieve your goals?",
    "What are the most important things you have learned in life so far?",
    "What does happiness mean to you?",
    "Am I holding onto something that is hurting me more than helping?",
    "Think of your life 15-20 years from now. What do you NOT want it to look like?",
    "What are the biggest challenges you’ve overcome in your life? How did you do it?",
    "Who are three people in my life that I am grateful for?",
    "What are your biggest weaknesses? How can you work to overcome them?",
    "What are you struggling with right now?"
]